on:
  pull_request:
  push:

name: ci

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: install elan
        run: |
          set -o pipefail
          curl -sSfL https://github.com/leanprover/elan/releases/download/v1.0.3/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
          ./elan-init -y
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - uses: actions/checkout@v2

      - name: build qq
        run: leanpkg build

      - name: run examples
        run: make examples
